name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
          
      - name: Build
        run: |
          npm run build
          touch out/.nojekyll
          cp CNAME out/
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          force: true
          commit-message: "Deploy: ${{ github.sha }}"
          git-config-name: IAmSpring
          git-config-email: IAmSpring@users.noreply.github.com